# base
env_name: CrawlerDynamicTarget
algo: sac
seed: 42
time_scale: 8
no_cuda: True
debug: False
save_dir: outputs/sac_crawler
load_path: outputs/sac_crawler

# sac
batch_size: 256
buffer_size: 500000
T: 1024
T_EPS: 2048
learning_rate: 0.0003
gamma: 0.995
tau: 0.005
actor_hidden_layers: [512, 512, 512]
critic_hidden_layers: [512, 512, 512]
normalize: True
save_steps: 5